In [ ]:
import sys
assert sys.version_info >= (3, 5)

IS_COLAB = "google.colab" in sys.modules

if IS_COLAB:
  !apt update && apt install -y libpq-dev libsdl2-dev swig xorg-dev xvfb
  %pip install -U tf-agents pyvirtualdisplay
  %pip install -U gym>=0.21.0
  %pip install -U gym[box2d,atari,accept-rom-license]

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Get:2 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:8 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:14 http://ppa.launchpad.net/c2d4u.te

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-agents 0.14.0 requires gym<=0.23.0,>=0.17.0, but you have gym 0.26.0 which is incompatible.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import sklearn
assert sklearn.__version__ >= "0.20"

In [ ]:
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

In [ ]:
if not tf.config.list_physical_devices("GPU"):
  print("GPU not found")
  if IS_COLAB:
    print("하드웨어 가속기를 GPU로 변경")

In [ ]:
import numpy as np
import os

np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rc("axes", labelsize = 14)
mpl.rc("xtick", labelsize = 12)
mpl.rc("ytick", labelsize = 12)

In [ ]:
#부드러운 애니메이션 실행을 위해
import matplotlib.animation as animation
mpl.rc('animation', html = 'jshtml')

In [ ]:
#그림을 저장할 위치
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "rl"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok = True)

In [ ]:
def save_fig(fig_id, tight_layout = True, fig_extension='png', resolution=300):
  path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
  print("save image", fig_id)
  if tight_layout:
    plt.tight_layout()
  plt.savefig(path, format = fig_extension, dpi=resolution)

In [ ]:
import gym

In [ ]:
gym.__version__

'0.26.0'

In [ ]:
env = gym.make('CartPole-v1', render_mode = "rgb_array")

reset :  환경을 초기화, 관측값을 반환해줌

In [ ]:
env.action_space.seed(42)
obs = env.reset()

In [ ]:
obs

(array([ 0.01919069,  0.03659717, -0.0454498 , -0.04204129], dtype=float32),
 {})

관측은 환경에 따라 달라짐,  
  

4개의 실수로 구성된 1D 넘파이 배열,  
카트의

(수평위치 , 속도, 막대의 각도(0=수직), 각속도)

를 나타냄  

환경은 render() 메서드를 호출하여 시각화할 수 있습니다.   
그리고 렌더링 모드(환경에 따른 렌더링 옵션)를 선택할 수 있습니다.  
  
경고: (Cart-Pole을 포함해) 일부 환경은 화면 접근 권한이 필요합니다.   
mode="rgb_array"로 지정하더라도 별도의 윈도우를 엽니다.  
일반적으로 이 윈도우를 무시할 수 있습니다. 하지만 주피터를 백엔드(headless) 서버로 실행한다면 예외가 발생합니다. 이를 피하는 한 가지 방법은 Xvfb 같은 가짜 X 서버를 설치하는 것입니다. 데비안이나 우분투에서는 다음과 같이 설치합니다:  
  
$ apt update
$ apt install -y xvfb
그다음 xvfb-run 명령으로 주피터를 실행합니다:
  
$ xvfb-run -s "-screen 0 1400x900x24" jupyter notebook
또는 Xvfb를 감싼 pyvirtualdisplay 파이썬 라이브러리를 설치할 수 있습니다:

%pip install -U pyvirtualdisplay
그다음 다음 코드를 실행합니다:

In [ ]:
try:
  import pyvirtualdisplay
  display = pyvirtualdisplay.Display(visible=0, size = (1400, 900)).start()
except ImportError:
  pass

In [ ]:
help(env.render)

Help on method render in module gym.core:

render(*args, **kwargs) -> Union[~RenderFrame, List[~RenderFrame], NoneType] method of gym.wrappers.time_limit.TimeLimit instance
    Renders the environment.



In [ ]:
img = env.render()
img.shape

(400, 600, 3)

In [ ]:
env.action_space

Discrete(2)

In [ ]:
action = 1

In [ ]:
res = env.step(action)
observation = res[0]
reward = res[1]
done = res[2]
info = res[3]
print(res[0]) #관측값
print(res[1]) #reward
print(res[2]) #done
print(res[3]) #info
print(res[4]) #

[ 0.01992263  0.2323404  -0.04629062 -0.34871057]
1.0
False
False
{}


In [ ]:
print(res)

(array([ 0.01992263,  0.2323404 , -0.04629062, -0.34871057], dtype=float32), 1.0, False, False, {})


In [ ]:
obs

(array([ 0.01919069,  0.03659717, -0.0454498 , -0.04204129], dtype=float32),
 {})

In [ ]:
type(obs)

tuple

In [ ]:
def basic_policy(obs):
  angle = obs[2]
  return 0 if angle < 0 else 1

In [ ]:
totals = []

for episode in range(500):
  episode_rewards = 0
  observation = env.reset()
  #print(observaiton)

  for step in range(200):
    action = basic_policy(observation)
    res = env.step(action)
    obs = res[0]
    reward = res[1]
    done = res[2]
    info = res[3]
    episode_rewards += reward
    if done:
      break

  totals.append(episode_rewards)

IndexError: ignored

#basic policy 문제

In [56]:
import tensorflow as tf
from tensorflow import keras

n_inputs = 4 #env.observation_space.shape[0] # 관측공간의 크기

model = keras.models.Sequential([
    keras.layers.Dense(5, activation="elu", input_shape = [n_inputs]),
    keras.layers.Dense(1, activation="sigmoid"),
])

In [57]:
def play_one_step(env,obs, model, loss_fn):
  with tf.GradientTape() as tape:
    left_proba = model(obs[np.newaxis])
    action = (tf.random.uniform([1, 1]) > left_proba)
    y_target = tf.constant([[1.]]) - tf.cast(action, tf.float32)
    loss = tf.reduce_mean(loss_fn(y_target, left_proba))
  grads = tape.gradient(loss, model.trainable_variables)
  obs, reward, done, info = env.step(int(action[0, 0].numpy()))
  return obs, reward, done, grads